# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'unturned_dedicated_server_windowWJXbzL.ui'
##
## Created by: Qt User Interface Compiler version 5.15.5
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *  # type: ignore
from PyQt5.QtGui import *  # type: ignore
from PyQt5.QtWidgets import *  # type: ignore


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(375, 425)
        Form.setStyleSheet(u"")
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 375, 425))
        self.tabWidget.setFocusPolicy(Qt.NoFocus)
        self.tabWidget.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.tabWidget.setStyleSheet(u"font: 75 12.5pt \"NSimSun\";")
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setElideMode(Qt.ElideMiddle)
        self.tabWidget.setTabBarAutoHide(True)
        self.tab_open = QWidget()
        self.tab_open.setObjectName(u"tab_open")
        self.background = QFrame(self.tab_open)
        self.background.setObjectName(u"background")
        self.background.setGeometry(QRect(0, 0, 375, 410))
        self.background.setFocusPolicy(Qt.NoFocus)
        self.background.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.477, y1:1, x2:0.471, y2:0, stop:0.295455 rgba(25, 25, 25, 255), stop:1 rgba(50, 50, 50, 255));")
        self.background.setFrameShape(QFrame.Box)
        self.background.setFrameShadow(QFrame.Raised)
        self.steam_location_label = QLabel(self.background)
        self.steam_location_label.setObjectName(u"steam_location_label")
        self.steam_location_label.setGeometry(QRect(30, 50, 311, 31))
        self.steam_location_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";")
        self.steam_location_full = QLineEdit(self.background)
        self.steam_location_full.setObjectName(u"steam_location_full")
        self.steam_location_full.setGeometry(QRect(90, 80, 201, 31))
        self.steam_location_full.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.steam_location_full.setAlignment(Qt.AlignCenter)
        self.steam_location_cdef = QComboBox(self.background)
        self.steam_location_cdef.addItem("")
        self.steam_location_cdef.addItem("")
        self.steam_location_cdef.addItem("")
        self.steam_location_cdef.setObjectName(u"steam_location_cdef")
        self.steam_location_cdef.setGeometry(QRect(30, 80, 51, 31))
        self.steam_location_cdef.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.select_server_label = QLabel(self.background)
        self.select_server_label.setObjectName(u"select_server_label")
        self.select_server_label.setGeometry(QRect(30, 250, 311, 31))
        self.select_server_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";")
        self.select_server_choose = QComboBox(self.background)
        self.select_server_choose.addItem("")
        self.select_server_choose.addItem("")
        self.select_server_choose.setObjectName(u"select_server_choose")
        self.select_server_choose.setGeometry(QRect(30, 280, 151, 31))
        self.select_server_choose.setMouseTracking(False)
        self.select_server_choose.setTabletTracking(False)
        self.select_server_choose.setAcceptDrops(False)
        self.select_server_choose.setLayoutDirection(Qt.LeftToRight)
        self.select_server_choose.setAutoFillBackground(False)
        self.select_server_choose.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.select_server_choose.setEditable(False)
        self.select_server_choose.setDuplicatesEnabled(False)
        self.select_server_choose.setFrame(True)
        self.login_token_label = QLabel(self.background)
        self.login_token_label.setObjectName(u"login_token_label")
        self.login_token_label.setGeometry(QRect(30, 150, 311, 31))
        self.login_token_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";")
        self.select_server_open = QPushButton(self.background)
        self.select_server_open.setObjectName(u"select_server_open")
        self.select_server_open.setGeometry(QRect(190, 280, 151, 31))
        self.select_server_open.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.login_token_input = QLineEdit(self.background)
        self.login_token_input.setObjectName(u"login_token_input")
        self.login_token_input.setGeometry(QRect(30, 180, 261, 31))
        self.login_token_input.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.login_token_input.setAlignment(Qt.AlignCenter)
        self.steam_location_find = QToolButton(self.background)
        self.steam_location_find.setObjectName(u"steam_location_find")
        self.steam_location_find.setGeometry(QRect(300, 80, 41, 31))
        self.steam_location_find.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.login_token_web = QPushButton(self.background)
        self.login_token_web.setObjectName(u"login_token_web")
        self.login_token_web.setGeometry(QRect(300, 180, 41, 31))
        self.login_token_web.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.tabWidget.addTab(self.tab_open, "")
        self.tab_option = QWidget()
        self.tab_option.setObjectName(u"tab_option")
        self.background_2 = QFrame(self.tab_option)
        self.background_2.setObjectName(u"background_2")
        self.background_2.setGeometry(QRect(0, 0, 375, 410))
        self.background_2.setFocusPolicy(Qt.NoFocus)
        self.background_2.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.477, y1:1, x2:0.471, y2:0, stop:0.295455 rgba(25, 25, 25, 255), stop:1 rgba(50, 50, 50, 255));")
        self.background_2.setFrameShape(QFrame.Box)
        self.background_2.setFrameShadow(QFrame.Raised)
        self.file_name_label = QLabel(self.background_2)
        self.file_name_label.setObjectName(u"file_name_label")
        self.file_name_label.setGeometry(QRect(50, 10, 131, 31))
        self.file_name_label.setTabletTracking(False)
        self.file_name_label.setAutoFillBackground(False)
        self.file_name_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.file_name_label.setFrameShape(QFrame.NoFrame)
        self.file_name_label.setFrameShadow(QFrame.Plain)
        self.file_name_input = QLineEdit(self.background_2)
        self.file_name_input.setObjectName(u"file_name_input")
        self.file_name_input.setGeometry(QRect(50, 40, 131, 31))
        self.file_name_input.setStyleSheet(u"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(81, 81, 81);")
        self.file_name_input.setAlignment(Qt.AlignCenter)
        self.perspective_label = QLabel(self.background_2)
        self.perspective_label.setObjectName(u"perspective_label")
        self.perspective_label.setGeometry(QRect(50, 150, 51, 31))
        self.perspective_label.setTabletTracking(False)
        self.perspective_label.setAutoFillBackground(False)
        self.perspective_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.perspective_label.setFrameShape(QFrame.NoFrame)
        self.perspective_label.setFrameShadow(QFrame.Plain)
        self.map_label = QLabel(self.background_2)
        self.map_label.setObjectName(u"map_label")
        self.map_label.setGeometry(QRect(50, 80, 131, 31))
        self.map_label.setTabletTracking(False)
        self.map_label.setAutoFillBackground(False)
        self.map_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.map_label.setFrameShape(QFrame.NoFrame)
        self.map_label.setFrameShadow(QFrame.Plain)
        self.mode_label = QLabel(self.background_2)
        self.mode_label.setObjectName(u"mode_label")
        self.mode_label.setGeometry(QRect(50, 230, 51, 31))
        self.mode_label.setTabletTracking(False)
        self.mode_label.setAutoFillBackground(False)
        self.mode_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.mode_label.setFrameShape(QFrame.NoFrame)
        self.mode_label.setFrameShadow(QFrame.Plain)
        self.difficulty_label = QLabel(self.background_2)
        self.difficulty_label.setObjectName(u"difficulty_label")
        self.difficulty_label.setGeometry(QRect(50, 190, 51, 31))
        self.difficulty_label.setTabletTracking(False)
        self.difficulty_label.setAutoFillBackground(False)
        self.difficulty_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.difficulty_label.setFrameShape(QFrame.NoFrame)
        self.difficulty_label.setFrameShadow(QFrame.Plain)
        self.perspective_choose = QComboBox(self.background_2)
        self.perspective_choose.addItem("")
        self.perspective_choose.setObjectName(u"perspective_choose")
        self.perspective_choose.setGeometry(QRect(100, 150, 81, 31))
        self.perspective_choose.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.map_input = QLineEdit(self.background_2)
        self.map_input.setObjectName(u"map_input")
        self.map_input.setGeometry(QRect(50, 110, 131, 31))
        self.map_input.setStyleSheet(u"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.map_input.setAlignment(Qt.AlignCenter)
        self.mode_choose = QComboBox(self.background_2)
        self.mode_choose.addItem("")
        self.mode_choose.addItem("")
        self.mode_choose.setObjectName(u"mode_choose")
        self.mode_choose.setGeometry(QRect(100, 230, 81, 31))
        self.mode_choose.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.difficulty_choose = QComboBox(self.background_2)
        self.difficulty_choose.addItem("")
        self.difficulty_choose.addItem("")
        self.difficulty_choose.addItem("")
        self.difficulty_choose.setObjectName(u"difficulty_choose")
        self.difficulty_choose.setGeometry(QRect(100, 190, 81, 31))
        self.difficulty_choose.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.workshop_label = QLabel(self.background_2)
        self.workshop_label.setObjectName(u"workshop_label")
        self.workshop_label.setGeometry(QRect(50, 270, 81, 31))
        self.workshop_label.setTabletTracking(False)
        self.workshop_label.setAutoFillBackground(False)
        self.workshop_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.workshop_label.setFrameShape(QFrame.NoFrame)
        self.workshop_label.setFrameShadow(QFrame.Plain)
        self.workshop_input = QLineEdit(self.background_2)
        self.workshop_input.setObjectName(u"workshop_input")
        self.workshop_input.setGeometry(QRect(130, 270, 201, 31))
        self.workshop_input.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.workshop_input.setAlignment(Qt.AlignCenter)
        self.workshop_choose = QComboBox(self.background_2)
        self.workshop_choose.setObjectName(u"workshop_choose")
        self.workshop_choose.setGeometry(QRect(130, 300, 91, 31))
        self.workshop_choose.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.anti_cheat_vac = QCheckBox(self.background_2)
        self.anti_cheat_vac.setObjectName(u"anti_cheat_vac")
        self.anti_cheat_vac.setGeometry(QRect(130, 340, 91, 31))
        self.anti_cheat_vac.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"NSimSun\";")
        self.anti_cheat_vac.setChecked(True)
        self.anti_cheat_vac.setTristate(False)
        self.anti_cheat_battleye = QCheckBox(self.background_2)
        self.anti_cheat_battleye.setObjectName(u"anti_cheat_battleye")
        self.anti_cheat_battleye.setGeometry(QRect(230, 340, 101, 31))
        self.anti_cheat_battleye.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"NSimSun\";")
        self.anti_cheat_battleye.setChecked(True)
        self.anti_cheat_label = QLabel(self.background_2)
        self.anti_cheat_label.setObjectName(u"anti_cheat_label")
        self.anti_cheat_label.setGeometry(QRect(50, 340, 81, 31))
        self.anti_cheat_label.setTabletTracking(False)
        self.anti_cheat_label.setAutoFillBackground(False)
        self.anti_cheat_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.anti_cheat_label.setFrameShape(QFrame.NoFrame)
        self.anti_cheat_label.setFrameShadow(QFrame.Plain)
        self.port_label = QLabel(self.background_2)
        self.port_label.setObjectName(u"port_label")
        self.port_label.setGeometry(QRect(200, 150, 41, 31))
        self.port_label.setTabletTracking(False)
        self.port_label.setAutoFillBackground(False)
        self.port_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.port_label.setFrameShape(QFrame.NoFrame)
        self.port_label.setFrameShadow(QFrame.Plain)
        self.maxplayers_label = QLabel(self.background_2)
        self.maxplayers_label.setObjectName(u"maxplayers_label")
        self.maxplayers_label.setGeometry(QRect(200, 190, 41, 31))
        self.maxplayers_label.setTabletTracking(False)
        self.maxplayers_label.setAutoFillBackground(False)
        self.maxplayers_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.maxplayers_label.setFrameShape(QFrame.NoFrame)
        self.maxplayers_label.setFrameShadow(QFrame.Plain)
        self.password_label = QLabel(self.background_2)
        self.password_label.setObjectName(u"password_label")
        self.password_label.setGeometry(QRect(200, 230, 41, 31))
        self.password_label.setTabletTracking(False)
        self.password_label.setAutoFillBackground(False)
        self.password_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.password_label.setFrameShape(QFrame.NoFrame)
        self.password_label.setFrameShadow(QFrame.Plain)
        self.maxplayers_choose = QComboBox(self.background_2)
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.addItem("")
        self.maxplayers_choose.setObjectName(u"maxplayers_choose")
        self.maxplayers_choose.setGeometry(QRect(250, 190, 81, 31))
        self.maxplayers_choose.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.port_input = QLineEdit(self.background_2)
        self.port_input.setObjectName(u"port_input")
        self.port_input.setGeometry(QRect(250, 150, 81, 31))
        self.port_input.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.port_input.setAlignment(Qt.AlignCenter)
        self.password_input = QLineEdit(self.background_2)
        self.password_input.setObjectName(u"password_input")
        self.password_input.setGeometry(QRect(250, 230, 81, 31))
        self.password_input.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.password_input.setAlignment(Qt.AlignCenter)
        self.welcome_input = QLineEdit(self.background_2)
        self.welcome_input.setObjectName(u"welcome_input")
        self.welcome_input.setGeometry(QRect(200, 110, 131, 31))
        self.welcome_input.setStyleSheet(u"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.welcome_input.setAlignment(Qt.AlignCenter)
        self.welcome_label = QLabel(self.background_2)
        self.welcome_label.setObjectName(u"welcome_label")
        self.welcome_label.setGeometry(QRect(200, 80, 131, 31))
        self.welcome_label.setTabletTracking(False)
        self.welcome_label.setAutoFillBackground(False)
        self.welcome_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.welcome_label.setFrameShape(QFrame.NoFrame)
        self.welcome_label.setFrameShadow(QFrame.Plain)
        self.workshop_add = QPushButton(self.background_2)
        self.workshop_add.setObjectName(u"workshop_add")
        self.workshop_add.setGeometry(QRect(220, 300, 51, 31))
        self.workshop_add.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.workshop_remove = QPushButton(self.background_2)
        self.workshop_remove.setObjectName(u"workshop_remove")
        self.workshop_remove.setGeometry(QRect(270, 300, 61, 31))
        self.workshop_remove.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.server_name_input = QLineEdit(self.background_2)
        self.server_name_input.setObjectName(u"server_name_input")
        self.server_name_input.setGeometry(QRect(200, 40, 131, 31))
        self.server_name_input.setStyleSheet(u"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.server_name_input.setAlignment(Qt.AlignCenter)
        self.server_name_label = QLabel(self.background_2)
        self.server_name_label.setObjectName(u"server_name_label")
        self.server_name_label.setGeometry(QRect(200, 10, 131, 31))
        self.server_name_label.setTabletTracking(False)
        self.server_name_label.setAutoFillBackground(False)
        self.server_name_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.server_name_label.setFrameShape(QFrame.NoFrame)
        self.server_name_label.setFrameShadow(QFrame.Plain)
        self.tabWidget.addTab(self.tab_option, "")
        self.tab_value = QWidget()
        self.tab_value.setObjectName(u"tab_value")
        self.background_3 = QFrame(self.tab_value)
        self.background_3.setObjectName(u"background_3")
        self.background_3.setGeometry(QRect(0, -10, 375, 410))
        self.background_3.setFocusPolicy(Qt.NoFocus)
        self.background_3.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.477, y1:1, x2:0.471, y2:0, stop:0.295455 rgba(25, 25, 25, 255), stop:1 rgba(50, 50, 50, 255));")
        self.background_3.setFrameShape(QFrame.Box)
        self.background_3.setFrameShadow(QFrame.Raised)
        self.server_subtitle_input = QLineEdit(self.background_3)
        self.server_subtitle_input.setObjectName(u"server_subtitle_input")
        self.server_subtitle_input.setGeometry(QRect(30, 50, 311, 31))
        self.server_subtitle_input.setStyleSheet(u"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.server_subtitle_input.setAlignment(Qt.AlignCenter)
        self.server_subtitle_label = QLabel(self.background_3)
        self.server_subtitle_label.setObjectName(u"server_subtitle_label")
        self.server_subtitle_label.setGeometry(QRect(30, 20, 311, 31))
        self.server_subtitle_label.setTabletTracking(False)
        self.server_subtitle_label.setAutoFillBackground(False)
        self.server_subtitle_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.server_subtitle_label.setFrameShape(QFrame.NoFrame)
        self.server_subtitle_label.setFrameShadow(QFrame.Plain)
        self.server_fulldesc_label = QLabel(self.background_3)
        self.server_fulldesc_label.setObjectName(u"server_fulldesc_label")
        self.server_fulldesc_label.setGeometry(QRect(30, 160, 311, 31))
        self.server_fulldesc_label.setTabletTracking(False)
        self.server_fulldesc_label.setAutoFillBackground(False)
        self.server_fulldesc_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.server_fulldesc_label.setFrameShape(QFrame.NoFrame)
        self.server_fulldesc_label.setFrameShadow(QFrame.Plain)
        self.list_server_subtitle_input = QLineEdit(self.background_3)
        self.list_server_subtitle_input.setObjectName(u"list_server_subtitle_input")
        self.list_server_subtitle_input.setGeometry(QRect(30, 120, 311, 31))
        self.list_server_subtitle_input.setStyleSheet(u"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.list_server_subtitle_input.setAlignment(Qt.AlignCenter)
        self.list_server_subtitle_label = QLabel(self.background_3)
        self.list_server_subtitle_label.setObjectName(u"list_server_subtitle_label")
        self.list_server_subtitle_label.setGeometry(QRect(30, 90, 311, 31))
        self.list_server_subtitle_label.setTabletTracking(False)
        self.list_server_subtitle_label.setAutoFillBackground(False)
        self.list_server_subtitle_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.list_server_subtitle_label.setFrameShape(QFrame.NoFrame)
        self.list_server_subtitle_label.setFrameShadow(QFrame.Plain)
        self.server_fulldesc_input = QTextEdit(self.background_3)
        self.server_fulldesc_input.setObjectName(u"server_fulldesc_input")
        self.server_fulldesc_input.setGeometry(QRect(30, 190, 311, 201))
        self.server_fulldesc_input.setStyleSheet(u"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.server_fulldesc_input.setFrameShape(QFrame.Box)
        self.tabWidget.addTab(self.tab_value, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.background_4 = QFrame(self.tab)
        self.background_4.setObjectName(u"background_4")
        self.background_4.setGeometry(QRect(0, 0, 375, 410))
        self.background_4.setFocusPolicy(Qt.NoFocus)
        self.background_4.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.477, y1:1, x2:0.471, y2:0, stop:0.295455 rgba(25, 25, 25, 255), stop:1 rgba(50, 50, 50, 255));")
        self.background_4.setFrameShape(QFrame.Box)
        self.background_4.setFrameShadow(QFrame.Raised)
        self.custom_difficulty_choose = QComboBox(self.background_4)
        self.custom_difficulty_choose.addItem("")
        self.custom_difficulty_choose.addItem("")
        self.custom_difficulty_choose.addItem("")
        self.custom_difficulty_choose.setObjectName(u"custom_difficulty_choose")
        self.custom_difficulty_choose.setGeometry(QRect(30, 120, 151, 31))
        self.custom_difficulty_choose.setLayoutDirection(Qt.LeftToRight)
        self.custom_difficulty_choose.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.custom_difficulty_label = QLabel(self.background_4)
        self.custom_difficulty_label.setObjectName(u"custom_difficulty_label")
        self.custom_difficulty_label.setGeometry(QRect(30, 90, 311, 31))
        self.custom_difficulty_label.setTabletTracking(False)
        self.custom_difficulty_label.setAutoFillBackground(False)
        self.custom_difficulty_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.custom_difficulty_label.setFrameShape(QFrame.NoFrame)
        self.custom_difficulty_label.setFrameShadow(QFrame.Plain)
        self.custom_option_choose = QComboBox(self.background_4)
        self.custom_option_choose.addItem("")
        self.custom_option_choose.addItem("")
        self.custom_option_choose.addItem("")
        self.custom_option_choose.addItem("")
        self.custom_option_choose.addItem("")
        self.custom_option_choose.addItem("")
        self.custom_option_choose.addItem("")
        self.custom_option_choose.addItem("")
        self.custom_option_choose.addItem("")
        self.custom_option_choose.addItem("")
        self.custom_option_choose.setObjectName(u"custom_option_choose")
        self.custom_option_choose.setGeometry(QRect(30, 200, 81, 31))
        self.custom_option_choose.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.custom_difficulty_option_label = QLabel(self.background_4)
        self.custom_difficulty_option_label.setObjectName(u"custom_difficulty_option_label")
        self.custom_difficulty_option_label.setGeometry(QRect(30, 170, 311, 31))
        self.custom_difficulty_option_label.setTabletTracking(False)
        self.custom_difficulty_option_label.setAutoFillBackground(False)
        self.custom_difficulty_option_label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.custom_difficulty_option_label.setFrameShape(QFrame.NoFrame)
        self.custom_difficulty_option_label.setFrameShadow(QFrame.Plain)
        self.custom_option_value = QLineEdit(self.background_4)
        self.custom_option_value.setObjectName(u"custom_option_value")
        self.custom_option_value.setGeometry(QRect(30, 240, 141, 31))
        self.custom_option_value.setStyleSheet(u"font: 75 10pt \"NSimSun\";\n"
"color: rgb(255, 255, 255);")
        self.custom_option_value.setAlignment(Qt.AlignCenter)
        self.custom_all_default = QPushButton(self.background_4)
        self.custom_all_default.setObjectName(u"custom_all_default")
        self.custom_all_default.setGeometry(QRect(190, 120, 151, 31))
        self.custom_all_default.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.custom_onlyone_default = QPushButton(self.background_4)
        self.custom_onlyone_default.setObjectName(u"custom_onlyone_default")
        self.custom_onlyone_default.setGeometry(QRect(260, 240, 81, 31))
        self.custom_onlyone_default.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.custom_option_modify_choose = QComboBox(self.background_4)
        self.custom_option_modify_choose.setObjectName(u"custom_option_modify_choose")
        self.custom_option_modify_choose.setGeometry(QRect(120, 200, 221, 31))
        self.custom_option_modify_choose.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.custom_modify_click = QPushButton(self.background_4)
        self.custom_modify_click.setObjectName(u"custom_modify_click")
        self.custom_modify_click.setGeometry(QRect(180, 240, 71, 31))
        self.custom_modify_click.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.background_5 = QFrame(self.tab_2)
        self.background_5.setObjectName(u"background_5")
        self.background_5.setGeometry(QRect(0, -10, 375, 410))
        self.background_5.setFocusPolicy(Qt.NoFocus)
        self.background_5.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.477, y1:1, x2:0.471, y2:0, stop:0.295455 rgba(25, 25, 25, 255), stop:1 rgba(50, 50, 50, 255));")
        self.background_5.setFrameShape(QFrame.Box)
        self.background_5.setFrameShadow(QFrame.Raised)
        self.cheat_allow_check = QCheckBox(self.background_5)
        self.cheat_allow_check.setObjectName(u"cheat_allow_check")
        self.cheat_allow_check.setGeometry(QRect(10, 20, 81, 21))
        self.cheat_allow_check.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"NSimSun\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(0)
        self.difficulty_choose.setCurrentIndex(1)
        self.workshop_choose.setCurrentIndex(-1)
        self.maxplayers_choose.setCurrentIndex(11)
        self.custom_difficulty_choose.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Unturned \u5c08\u7528\u4f3a\u670d\u5668", None))
        self.steam_location_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">U3DS \u8def\u5f91</span></p></body></html>", None))
        self.steam_location_full.setText(QCoreApplication.translate("Form", u"Steam\\steamapps\\common\\U3DS", None))
        self.steam_location_cdef.setItemText(0, QCoreApplication.translate("Form", u"C:\\", None))
        self.steam_location_cdef.setItemText(1, QCoreApplication.translate("Form", u"D:\\", None))
        self.steam_location_cdef.setItemText(2, QCoreApplication.translate("Form", u"E:\\", None))

        self.select_server_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u9078\u64c7\u4f3a\u670d\u5668</span></p></body></html>", None))
        self.select_server_choose.setItemText(0, QCoreApplication.translate("Form", u"\u7121", None))
        self.select_server_choose.setItemText(1, QCoreApplication.translate("Form", u"\u65b0\u5efa\u4f3a\u670d\u5668", None))

        self.login_token_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">LOGIN TOKEN</span></p></body></html>", None))
        self.select_server_open.setText(QCoreApplication.translate("Form", u"\u555f\u52d5", None))
        self.login_token_input.setText("")
        self.login_token_input.setPlaceholderText(QCoreApplication.translate("Form", u"\u203b\u5fc5\u586b", None))
        self.steam_location_find.setText(QCoreApplication.translate("Form", u"...", None))
        self.login_token_web.setText(QCoreApplication.translate("Form", u"\u8a2d\u5b9a", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_open), QCoreApplication.translate("Form", u"\u9078\u64c7", None))
        self.file_name_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u6a94\u6848\u540d\u7a31</span></p></body></html>", None))
        self.file_name_input.setText("")
        self.file_name_input.setPlaceholderText(QCoreApplication.translate("Form", u"file_name", None))
        self.perspective_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u8996\u89d2</span></p></body></html>", None))
        self.map_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u5730\u5716</span></p></body></html>", None))
        self.mode_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u6a21\u5f0f</span></p></body></html>", None))
        self.difficulty_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u96e3\u5ea6</span></p></body></html>", None))
        self.perspective_choose.setItemText(0, QCoreApplication.translate("Form", u"\u7121\u9650\u5236", None))

        self.map_input.setText("")
        self.map_input.setPlaceholderText(QCoreApplication.translate("Form", u"map (ex.PEI)", None))
        self.mode_choose.setItemText(0, QCoreApplication.translate("Form", u"PVE", None))
        self.mode_choose.setItemText(1, QCoreApplication.translate("Form", u"PVP", None))

        self.difficulty_choose.setItemText(0, QCoreApplication.translate("Form", u"\u7c21\u55ae", None))
        self.difficulty_choose.setItemText(1, QCoreApplication.translate("Form", u"\u666e\u901a", None))
        self.difficulty_choose.setItemText(2, QCoreApplication.translate("Form", u"\u56f0\u96e3", None))

        self.workshop_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u5de5\u4f5c\u574a</span></p></body></html>", None))
        self.workshop_input.setText("")
        self.workshop_input.setPlaceholderText(QCoreApplication.translate("Form", u"workshop ID", None))
        self.anti_cheat_vac.setText(QCoreApplication.translate("Form", u"VAC", None))
        self.anti_cheat_battleye.setText(QCoreApplication.translate("Form", u"BattlEye", None))
        self.anti_cheat_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u53cd\u4f5c\u5f0a</span></p></body></html>", None))
        self.port_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u57e0</span></p></body></html>", None))
        self.maxplayers_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u4eba\u6578</span></p></body></html>", None))
        self.password_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u5bc6\u78bc</span></p></body></html>", None))
        self.maxplayers_choose.setItemText(0, QCoreApplication.translate("Form", u"1", None))
        self.maxplayers_choose.setItemText(1, QCoreApplication.translate("Form", u"2", None))
        self.maxplayers_choose.setItemText(2, QCoreApplication.translate("Form", u"3", None))
        self.maxplayers_choose.setItemText(3, QCoreApplication.translate("Form", u"4", None))
        self.maxplayers_choose.setItemText(4, QCoreApplication.translate("Form", u"5", None))
        self.maxplayers_choose.setItemText(5, QCoreApplication.translate("Form", u"6", None))
        self.maxplayers_choose.setItemText(6, QCoreApplication.translate("Form", u"7", None))
        self.maxplayers_choose.setItemText(7, QCoreApplication.translate("Form", u"8", None))
        self.maxplayers_choose.setItemText(8, QCoreApplication.translate("Form", u"9", None))
        self.maxplayers_choose.setItemText(9, QCoreApplication.translate("Form", u"10", None))
        self.maxplayers_choose.setItemText(10, QCoreApplication.translate("Form", u"11", None))
        self.maxplayers_choose.setItemText(11, QCoreApplication.translate("Form", u"12", None))
        self.maxplayers_choose.setItemText(12, QCoreApplication.translate("Form", u"16", None))
        self.maxplayers_choose.setItemText(13, QCoreApplication.translate("Form", u"20", None))
        self.maxplayers_choose.setItemText(14, QCoreApplication.translate("Form", u"24", None))
        self.maxplayers_choose.setItemText(15, QCoreApplication.translate("Form", u"32", None))

        self.maxplayers_choose.setCurrentText(QCoreApplication.translate("Form", u"12", None))
        self.port_input.setText("")
        self.port_input.setPlaceholderText(QCoreApplication.translate("Form", u"port", None))
        self.password_input.setText("")
        self.password_input.setPlaceholderText(QCoreApplication.translate("Form", u"password", None))
        self.welcome_input.setText("")
        self.welcome_input.setPlaceholderText(QCoreApplication.translate("Form", u"welcome_message", None))
        self.welcome_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u8a0a\u606f</span></p></body></html>", None))
        self.workshop_add.setText(QCoreApplication.translate("Form", u"\u65b0\u589e", None))
        self.workshop_remove.setText(QCoreApplication.translate("Form", u"\u522a\u9664", None))
        self.server_name_input.setText("")
        self.server_name_input.setPlaceholderText(QCoreApplication.translate("Form", u"server_name", None))
        self.server_name_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u4f3a\u670d\u540d\u7a31</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_option), QCoreApplication.translate("Form", u"\u8a2d\u5b9a", None))
        self.server_subtitle_input.setText("")
        self.server_subtitle_input.setPlaceholderText(QCoreApplication.translate("Form", u"server_subtitle", None))
        self.server_subtitle_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u4f3a\u670d\u5668\u526f\u6a19\u984c</span></p></body></html>", None))
        self.server_fulldesc_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u8a73\u7d30\u8aaa\u660e</span></p></body></html>", None))
        self.list_server_subtitle_input.setText("")
        self.list_server_subtitle_input.setPlaceholderText(QCoreApplication.translate("Form", u"list_server_subtitle", None))
        self.list_server_subtitle_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u4f3a\u670d\u5668\u526f\u6a19\u984c (\u5217\u8868)</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_value), QCoreApplication.translate("Form", u"\u8aaa\u660e", None))
        self.custom_difficulty_choose.setItemText(0, QCoreApplication.translate("Form", u"\u7c21\u55ae", None))
        self.custom_difficulty_choose.setItemText(1, QCoreApplication.translate("Form", u"\u666e\u901a", None))
        self.custom_difficulty_choose.setItemText(2, QCoreApplication.translate("Form", u"\u56f0\u96e3", None))

        self.custom_difficulty_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u4f7f\u7528\u96e3\u5ea6</span></p></body></html>", None))
        self.custom_option_choose.setItemText(0, QCoreApplication.translate("Form", u"\u7269\u54c1", None))
        self.custom_option_choose.setItemText(1, QCoreApplication.translate("Form", u"\u8f09\u5177", None))
        self.custom_option_choose.setItemText(2, QCoreApplication.translate("Form", u"\u6bad\u5c4d", None))
        self.custom_option_choose.setItemText(3, QCoreApplication.translate("Form", u"\u52d5\u7269", None))
        self.custom_option_choose.setItemText(4, QCoreApplication.translate("Form", u"\u969c\u7919", None))
        self.custom_option_choose.setItemText(5, QCoreApplication.translate("Form", u"\u5efa\u7bc9", None))
        self.custom_option_choose.setItemText(6, QCoreApplication.translate("Form", u"\u73a9\u5bb6", None))
        self.custom_option_choose.setItemText(7, QCoreApplication.translate("Form", u"\u7269\u4ef6", None))
        self.custom_option_choose.setItemText(8, QCoreApplication.translate("Form", u"\u4e8b\u4ef6", None))
        self.custom_option_choose.setItemText(9, QCoreApplication.translate("Form", u"\u904a\u6232", None))

        self.custom_difficulty_option_label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">\u8a2d\u5b9a</span></p></body></html>", None))
        self.custom_option_value.setPlaceholderText(QCoreApplication.translate("Form", u"value", None))
        self.custom_all_default.setText(QCoreApplication.translate("Form", u"\u5168\u90e8\u9810\u8a2d", None))
        self.custom_onlyone_default.setText(QCoreApplication.translate("Form", u"\u9810\u8a2d\u6b64\u9078\u9805", None))
        self.custom_modify_click.setText(QCoreApplication.translate("Form", u"\u4fee\u6539", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"\u6578\u503c", None))
        self.cheat_allow_check.setText(QCoreApplication.translate("Form", u"\u5141\u8a31\u4f5c\u5f0a", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"\u6307\u4ee4", None))
    # retranslateUi

